platform :ios, "8.0"
use_frameworks!

target 'HeilambClient' do

pod 'Heimdall', :git => 'https://github.com/sinbadflyce/Heimdall.git'
pod 'Hashids-Swift', '~> 0.3.0'
pod 'RNCryptor', '~> 4.0.0'
pod 'AWSLambda'
pod 'AWSDynamoDB'
pod 'AWSCognito'
pod 'AWSIoT'
pod 'BluetoothKit', '~> 0.3.0'

end